/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKESP_WIFI_MANAGER_H
#define _MOCKESP_WIFI_MANAGER_H

#include "unity.h"
#include "esp_wifi_manager.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockesp_wifi_manager_Init(void);
void Mockesp_wifi_manager_Destroy(void);
void Mockesp_wifi_manager_Verify(void);




#define parseStuff_ExpectAndReturn(cmd, cmock_retval) parseStuff_CMockExpectAndReturn(__LINE__, cmd, cmock_retval)
void parseStuff_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmd, int cmock_to_return);
#define wifi_manager_connect_ExpectAndReturn(cmock_arg1, cmock_retval) wifi_manager_connect_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void wifi_manager_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_arg1, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
