/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_spi_driver_mocks.h"

static const char* CMockString_bus_config = "bus_config";
static const char* CMockString_code = "code";
static const char* CMockString_dev_config = "dev_config";
static const char* CMockString_dma_chan = "dma_chan";
static const char* CMockString_esp_err_to_name = "esp_err_to_name";
static const char* CMockString_handle = "handle";
static const char* CMockString_host_id = "host_id";
static const char* CMockString_spi_bus_add_device = "spi_bus_add_device";
static const char* CMockString_spi_bus_initialize = "spi_bus_initialize";

typedef struct _CMOCK_spi_bus_add_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  spi_host_device_t Expected_host_id;
  const spi_device_interface_config_t* Expected_dev_config;
  spi_device_handle_t* Expected_handle;
  CEXCEPTION_T ExceptionToThrow;
  char ReturnThruPtr_handle_Used;
  spi_device_handle_t* ReturnThruPtr_handle_Val;
  size_t ReturnThruPtr_handle_Size;
  char IgnoreArg_host_id;
  char IgnoreArg_dev_config;
  char IgnoreArg_handle;

} CMOCK_spi_bus_add_device_CALL_INSTANCE;

typedef struct _CMOCK_spi_bus_initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  esp_err_t ReturnVal;
  spi_host_device_t Expected_host_id;
  const spi_bus_config_t* Expected_bus_config;
  spi_dma_chan_t Expected_dma_chan;
  CEXCEPTION_T ExceptionToThrow;
  char IgnoreArg_host_id;
  char IgnoreArg_bus_config;
  char IgnoreArg_dma_chan;

} CMOCK_spi_bus_initialize_CALL_INSTANCE;

typedef struct _CMOCK_esp_err_to_name_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  char* ReturnVal;
  esp_err_t Expected_code;
  CEXCEPTION_T ExceptionToThrow;
  char IgnoreArg_code;

} CMOCK_esp_err_to_name_CALL_INSTANCE;

static struct mock_spi_driver_mocksInstance
{
  char spi_bus_add_device_IgnoreBool;
  esp_err_t spi_bus_add_device_FinalReturn;
  char spi_bus_add_device_CallbackBool;
  CMOCK_spi_bus_add_device_CALLBACK spi_bus_add_device_CallbackFunctionPointer;
  int spi_bus_add_device_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE spi_bus_add_device_CallInstance;
  char spi_bus_initialize_IgnoreBool;
  esp_err_t spi_bus_initialize_FinalReturn;
  char spi_bus_initialize_CallbackBool;
  CMOCK_spi_bus_initialize_CALLBACK spi_bus_initialize_CallbackFunctionPointer;
  int spi_bus_initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE spi_bus_initialize_CallInstance;
  char esp_err_to_name_IgnoreBool;
  char* esp_err_to_name_FinalReturn;
  char esp_err_to_name_CallbackBool;
  CMOCK_esp_err_to_name_CALLBACK esp_err_to_name_CallbackFunctionPointer;
  int esp_err_to_name_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_err_to_name_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_spi_driver_mocks_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.spi_bus_add_device_CallInstance;
  if (Mock.spi_bus_add_device_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_bus_add_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.spi_bus_add_device_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.spi_bus_initialize_CallInstance;
  if (Mock.spi_bus_initialize_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_bus_initialize);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.spi_bus_initialize_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_err_to_name_CallInstance;
  if (Mock.esp_err_to_name_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_err_to_name);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_err_to_name_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_spi_driver_mocks_Init(void)
{
  mock_spi_driver_mocks_Destroy();
}

void mock_spi_driver_mocks_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t spi_bus_add_device(spi_host_device_t host_id, const spi_device_interface_config_t* dev_config, spi_device_handle_t* handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_bus_add_device);
  cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_bus_add_device_CallInstance);
  Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemNext(Mock.spi_bus_add_device_CallInstance);
  if (Mock.spi_bus_add_device_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.spi_bus_add_device_FinalReturn;
    memcpy((void*)(&Mock.spi_bus_add_device_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.spi_bus_add_device_CallbackBool &&
      Mock.spi_bus_add_device_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.spi_bus_add_device_CallbackFunctionPointer(host_id, dev_config, handle, Mock.spi_bus_add_device_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_host_id)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_add_device,CMockString_host_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_host_id), (void*)(&host_id), sizeof(spi_host_device_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dev_config)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_add_device,CMockString_dev_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_dev_config), (void*)(dev_config), sizeof(const spi_device_interface_config_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_handle)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_add_device,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_handle), (void*)(handle), sizeof(spi_device_handle_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.spi_bus_add_device_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.spi_bus_add_device_CallbackFunctionPointer(host_id, dev_config, handle, Mock.spi_bus_add_device_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_handle_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(handle, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)handle, (void*)cmock_call_instance->ReturnThruPtr_handle_Val,
      cmock_call_instance->ReturnThruPtr_handle_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_bus_add_device(CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance, spi_host_device_t host_id, const spi_device_interface_config_t* dev_config, spi_device_handle_t* handle);
void CMockExpectParameters_spi_bus_add_device(CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance, spi_host_device_t host_id, const spi_device_interface_config_t* dev_config, spi_device_handle_t* handle)
{
  memcpy((void*)(&cmock_call_instance->Expected_host_id), (void*)(&host_id),
         sizeof(spi_host_device_t[sizeof(host_id) == sizeof(spi_host_device_t) ? 1 : -1])); /* add spi_host_device_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_host_id = 0;
  cmock_call_instance->Expected_dev_config = dev_config;
  cmock_call_instance->IgnoreArg_dev_config = 0;
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->IgnoreArg_handle = 0;
  cmock_call_instance->ReturnThruPtr_handle_Used = 0;
}

void spi_bus_add_device_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_add_device_CALL_INSTANCE));
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_add_device_CallInstance, cmock_guts_index);
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.spi_bus_add_device_IgnoreBool = (char)1;
}

void spi_bus_add_device_CMockStopIgnore(void)
{
  if(Mock.spi_bus_add_device_IgnoreBool)
    Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemNext(Mock.spi_bus_add_device_CallInstance);
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
}

void spi_bus_add_device_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_add_device_CALL_INSTANCE));
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_add_device_CallInstance, cmock_guts_index);
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void spi_bus_add_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, spi_host_device_t host_id, const spi_device_interface_config_t* dev_config, spi_device_handle_t* handle, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_add_device_CALL_INSTANCE));
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_add_device_CallInstance, cmock_guts_index);
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_spi_bus_add_device(cmock_call_instance, host_id, dev_config, handle);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void spi_bus_add_device_AddCallback(CMOCK_spi_bus_add_device_CALLBACK Callback)
{
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  Mock.spi_bus_add_device_CallbackBool = (char)1;
  Mock.spi_bus_add_device_CallbackFunctionPointer = Callback;
}

void spi_bus_add_device_Stub(CMOCK_spi_bus_add_device_CALLBACK Callback)
{
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  Mock.spi_bus_add_device_CallbackBool = (char)0;
  Mock.spi_bus_add_device_CallbackFunctionPointer = Callback;
}

void spi_bus_add_device_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, spi_host_device_t host_id, const spi_device_interface_config_t* dev_config, spi_device_handle_t* handle, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_add_device_CALL_INSTANCE));
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_add_device_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_add_device_CallInstance, cmock_guts_index);
  Mock.spi_bus_add_device_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_spi_bus_add_device(cmock_call_instance, host_id, dev_config, handle);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void spi_bus_add_device_CMockReturnMemThruPtr_handle(UNITY_LINE_TYPE cmock_line, spi_device_handle_t* handle, size_t cmock_size)
{
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_add_device_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_handle_Used = 1;
  cmock_call_instance->ReturnThruPtr_handle_Val = handle;
  cmock_call_instance->ReturnThruPtr_handle_Size = cmock_size;
}

void spi_bus_add_device_CMockIgnoreArg_host_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_add_device_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_host_id = 1;
}

void spi_bus_add_device_CMockIgnoreArg_dev_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_add_device_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev_config = 1;
}

void spi_bus_add_device_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_add_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_add_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_add_device_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handle = 1;
}

esp_err_t spi_bus_initialize(spi_host_device_t host_id, const spi_bus_config_t* bus_config, spi_dma_chan_t dma_chan)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_bus_initialize);
  cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_bus_initialize_CallInstance);
  Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemNext(Mock.spi_bus_initialize_CallInstance);
  if (Mock.spi_bus_initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.spi_bus_initialize_FinalReturn;
    memcpy((void*)(&Mock.spi_bus_initialize_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.spi_bus_initialize_CallbackBool &&
      Mock.spi_bus_initialize_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.spi_bus_initialize_CallbackFunctionPointer(host_id, bus_config, dma_chan, Mock.spi_bus_initialize_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_host_id)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_initialize,CMockString_host_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_host_id), (void*)(&host_id), sizeof(spi_host_device_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_bus_config)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_initialize,CMockString_bus_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bus_config), (void*)(bus_config), sizeof(const spi_bus_config_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dma_chan)
  {
    UNITY_SET_DETAILS(CMockString_spi_bus_initialize,CMockString_dma_chan);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dma_chan), (void*)(&dma_chan), sizeof(spi_dma_chan_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.spi_bus_initialize_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.spi_bus_initialize_CallbackFunctionPointer(host_id, bus_config, dma_chan, Mock.spi_bus_initialize_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_bus_initialize(CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance, spi_host_device_t host_id, const spi_bus_config_t* bus_config, spi_dma_chan_t dma_chan);
void CMockExpectParameters_spi_bus_initialize(CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance, spi_host_device_t host_id, const spi_bus_config_t* bus_config, spi_dma_chan_t dma_chan)
{
  memcpy((void*)(&cmock_call_instance->Expected_host_id), (void*)(&host_id),
         sizeof(spi_host_device_t[sizeof(host_id) == sizeof(spi_host_device_t) ? 1 : -1])); /* add spi_host_device_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_host_id = 0;
  cmock_call_instance->Expected_bus_config = bus_config;
  cmock_call_instance->IgnoreArg_bus_config = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dma_chan), (void*)(&dma_chan),
         sizeof(spi_dma_chan_t[sizeof(dma_chan) == sizeof(spi_dma_chan_t) ? 1 : -1])); /* add spi_dma_chan_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dma_chan = 0;
}

void spi_bus_initialize_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_initialize_CALL_INSTANCE));
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_initialize_CallInstance, cmock_guts_index);
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.spi_bus_initialize_IgnoreBool = (char)1;
}

void spi_bus_initialize_CMockStopIgnore(void)
{
  if(Mock.spi_bus_initialize_IgnoreBool)
    Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemNext(Mock.spi_bus_initialize_CallInstance);
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
}

void spi_bus_initialize_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_initialize_CALL_INSTANCE));
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_initialize_CallInstance, cmock_guts_index);
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void spi_bus_initialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, spi_host_device_t host_id, const spi_bus_config_t* bus_config, spi_dma_chan_t dma_chan, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_initialize_CALL_INSTANCE));
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_initialize_CallInstance, cmock_guts_index);
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_spi_bus_initialize(cmock_call_instance, host_id, bus_config, dma_chan);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void spi_bus_initialize_AddCallback(CMOCK_spi_bus_initialize_CALLBACK Callback)
{
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  Mock.spi_bus_initialize_CallbackBool = (char)1;
  Mock.spi_bus_initialize_CallbackFunctionPointer = Callback;
}

void spi_bus_initialize_Stub(CMOCK_spi_bus_initialize_CALLBACK Callback)
{
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  Mock.spi_bus_initialize_CallbackBool = (char)0;
  Mock.spi_bus_initialize_CallbackFunctionPointer = Callback;
}

void spi_bus_initialize_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, spi_host_device_t host_id, const spi_bus_config_t* bus_config, spi_dma_chan_t dma_chan, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_bus_initialize_CALL_INSTANCE));
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_bus_initialize_CallInstance = CMock_Guts_MemChain(Mock.spi_bus_initialize_CallInstance, cmock_guts_index);
  Mock.spi_bus_initialize_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_spi_bus_initialize(cmock_call_instance, host_id, bus_config, dma_chan);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void spi_bus_initialize_CMockIgnoreArg_host_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_initialize_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_host_id = 1;
}

void spi_bus_initialize_CMockIgnoreArg_bus_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_initialize_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bus_config = 1;
}

void spi_bus_initialize_CMockIgnoreArg_dma_chan(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_spi_bus_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_bus_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.spi_bus_initialize_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dma_chan = 1;
}

char* esp_err_to_name(esp_err_t code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_err_to_name);
  cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_err_to_name_CallInstance);
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemNext(Mock.esp_err_to_name_CallInstance);
  if (Mock.esp_err_to_name_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_err_to_name_FinalReturn;
    Mock.esp_err_to_name_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_err_to_name_CallbackBool &&
      Mock.esp_err_to_name_CallbackFunctionPointer != NULL)
  {
    char* cmock_cb_ret = Mock.esp_err_to_name_CallbackFunctionPointer(code, Mock.esp_err_to_name_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_code)
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name,CMockString_code);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_code), (void*)(&code), sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.esp_err_to_name_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_err_to_name_CallbackFunctionPointer(code, Mock.esp_err_to_name_CallbackCalls++);
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code);
void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code)
{
  memcpy((void*)(&cmock_call_instance->Expected_code), (void*)(&code),
         sizeof(esp_err_t[sizeof(code) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_code = 0;
}

void esp_err_to_name_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_err_to_name_IgnoreBool = (char)1;
}

void esp_err_to_name_CMockStopIgnore(void)
{
  if(Mock.esp_err_to_name_IgnoreBool)
    Mock.esp_err_to_name_CallInstance = CMock_Guts_MemNext(Mock.esp_err_to_name_CallInstance);
  Mock.esp_err_to_name_IgnoreBool = (char)0;
}

void esp_err_to_name_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void esp_err_to_name_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t code, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_esp_err_to_name(cmock_call_instance, code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_err_to_name_AddCallback(CMOCK_esp_err_to_name_CALLBACK Callback)
{
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  Mock.esp_err_to_name_CallbackBool = (char)1;
  Mock.esp_err_to_name_CallbackFunctionPointer = Callback;
}

void esp_err_to_name_Stub(CMOCK_esp_err_to_name_CALLBACK Callback)
{
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  Mock.esp_err_to_name_CallbackBool = (char)0;
  Mock.esp_err_to_name_CallbackFunctionPointer = Callback;
}

void esp_err_to_name_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, esp_err_t code, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  Mock.esp_err_to_name_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_esp_err_to_name(cmock_call_instance, code);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void esp_err_to_name_CMockIgnoreArg_code(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_err_to_name_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_code = 1;
}

