---
:cmock:
  :plugins:
    - :ignore
    - :callback
    - :cexception
  :includes: []
  :mock_path: ./mocks
  :mock_prefix: mock_
  :treat_inlines: :include
  :framework: unity
  :includes:
    - stdio.h