/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKLCD_CONTROLLER_H
#define _MOCKLCD_CONTROLLER_H

#include "unity.h"
#include "lcd_controller.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocklcd_controller_Init(void);
void Mocklcd_controller_Destroy(void);
void Mocklcd_controller_Verify(void);




#define lcd_spi_pre_transfer_callback_Expect(t) lcd_spi_pre_transfer_callback_CMockExpect(__LINE__, t)
void lcd_spi_pre_transfer_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, spi_transaction_t* t);
#define init_lcd_ExpectAndReturn(cmock_retval) init_lcd_CMockExpectAndReturn(__LINE__, cmock_retval)
void init_lcd_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define lcd_reset_ExpectAndReturn(cmock_arg1, cmock_retval) lcd_reset_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void lcd_reset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_arg1, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
