name: Build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build esp32_release
        run: platformio run -e esp32_release


  macOS:
    runs-on: macos-latest
    steps:
      - name: Install macOS dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build esp32_release
        run: platformio run -e esp32_release


  Windows:
    runs-on: windows-2019
    steps:
      - name: Activate msys2 & mingw64
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install deps
        run: |
          pacman --noconfirm -S --needed mingw-w64-x86_64-SDL2
          gcc --version

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build esp32_release
        run: platformio run -e esp32_release
      - name: Build native_sdl
        run: platformio run -e native_sdl
