name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Install platformIO libraries
        run: pio lib install
      - name: Run desktop test
        run: pio test --environment native
      - name: Run embedded tests
        run: pio test --environment esp-wrover-kit-test
      - name: Build PlatformIO Project
        run: pio run --environment default
